BEGIN;

WITH inserted_id AS (
    INSERT INTO
        cqc."User"(
            "FullNameValue",
            "JobTitleValue",
            "EmailValue",
            "PhoneValue",
            "EstablishmentID",
            "UserRoleValue",
            "UserRoleSavedAt",
            "UserRoleChangedAt",
            "UserRoleSavedBy",
            "UserRoleChangedBy",
            "SecurityQuestionValue",
            "SecurityQuestionAnswerValue",
            "FullNameChangedAt",
            "FullNameSavedBy",
            "FullNameChangedBy",
            "JobTitleSavedAt",
            "JobTitleChangedAt",
            "JobTitleSavedBy",
            "JobTitleChangedBy",
            "EmailSavedAt",
            "EmailChangedAt",
            "EmailSavedBy",
            "EmailChangedBy",
            "PhoneSavedAt",
            "PhoneChangedAt",
            "PhoneSavedBy",
            "PhoneChangedBy",
            "SecurityQuestionSavedAt",
            "SecurityQuestionChangedAt",
            "SecurityQuestionSavedBy",
            "SecurityQuestionChangedBy",
            "SecurityQuestionAnswerSavedAt",
            "SecurityQuestionAnswerChangedAt",
            "SecurityQuestionAnswerSavedBy",
            "SecurityQuestionAnswerChangedBy",
            "FullNameSavedAt",
            created,
            updated,
            updatedby,
            "Archived",
            "UserUID",
            "IsPrimary",
            "TribalID",
            "TribalPasswordAnswer",
            "LaReportLockHeld",
            "RegistrationSurveyCompleted"
        )
    VALUES
        (
            '<name>',
            'Skills for Care Admin',
            '<email>',
            '<number>',
            NULL,
            '<role>',
            NULL,
            NULL,
            NULL,
            NULL,
            '',
            '',
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            NULL,
            NOW(),
            NOW(),
            'admin1',
            False,
            gen_random_uuid(),
            True,
            NULL,
            NULL,
            False,
            True
        ) RETURNING "RegistrationID"
)
INSERT INTO
    cqc."Login"(
        "RegistrationID",
        "Username",
        "Active",
        "InvalidAttempt",
        "Hash",
        "FirstLogin",
        "PasswdLastChanged",
        "LastLoggedIn",
        "TribalHash",
        "TribalSalt",
        "Status",
        "AgreedUpdatedTerms"
    )
VALUES
    (
        (
            select
                "RegistrationID"
            from
                inserted_id
        ),
        'admin<name>',
        True,
        0,
        '<hashed password>',
        NULL,
        NOW(),
        NULL,
        NULL,
        NULL,
        NULL,
        True
    );

COMMIT;